name: Workflow learning
on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  Automatic-Tag-Version-Increment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # needed to access previous tags
      
      - name: Get latest tag
        id: get_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Bump Patch Version # note that space
        id: bump_tag
        run: |
          latest_tag=${{ steps.get_tag.outputs.latest_tag }}
          IFS='.' read -r -a parts <<< "${latest_tag#v}"
          new_tag="v${parts[0]}.${parts[1]}.$((parts[2] + 1))"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Create and Push New Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag ${{ steps.bump_tag.outputs.new_tag }}
          git push origin ${{ steps.bump_tag.outputs.new_tag }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      
      - name: Login to Amazon ECR Public Repository
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR Public
        env: 
          REGISTRY_TYPE: ${{ steps.login-ecr-public.outputs.registry }}
          REPOSITORY_NAME: ${{ secrets.AWS_ECR_REPO_NAME }}
          IMAGE_TAG: ${{ steps.bump_tag.outputs.new_tag }}
        run: |
          echo "Full Name: $REGISTRY_TYPE/$REPOSITORY_NAME:$IMAGE_TAG ."
          docker build -t "$REGISTRY_TYPE/$REPOSITORY_NAME:$IMAGE_TAG" .
          docker push "$REGISTRY_TYPE/$REPOSITORY_NAME:$IMAGE_TAG"
