name: Pr Check
on:
  pull_request :
    branches:
      - main

jobs: 
  CheckJob:
    runs-on: ubuntu-latest 
    steps:
      - name: Clone Repository
        uses: actions/checkout@v5
      
      # - name: Setup Java
      #   uses: actions/setup-java@v5
      #   with:
      #     distribution: 'corretto'
      #     java-version: '21'
      
      # - name: Cache Maven dependencies
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.m2/repository
      #     key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-maven-
          
      # - name: Bulid with Maven
      #   run: mvn clean install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR Public
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          # REGISTRY_ALIAS: my-ecr-public-registry-alias
          REPOSITORY: ${{secrets.AWS_ECR_REPO_NAME}}
          # IMAGE_TAG: ${{ github.sha }}
          IMAGE_TAG: latest
        run: |
          docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
        
